# Generated by Django 5.2.1 on 2025-05-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_categories_options_alter_categories_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="name",
            field=models.CharField(
                default="Unnamed Category",
                max_length=150,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Quantity"),
        ),
    ]
