# Generated by Django 5.2.1 on 2025-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_categories_name_alter_products_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="name",
            field=models.CharField(
                default="default_name", max_length=150, unique=True, verbose_name="Name"
            ),
        ),
    ]
